### ISSUE TITLE
There is a issue When predict with the bisenet 

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#1015]
When I  pridict wiht the bisent,threre came a problem:
`RuntimeError: (NotFound) Operator conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[CUDNN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:128)
  [operator < conv2d > error]`
I don't know how to deal it, whether there is a yml's template  for predict

**Comment by lingorX** [comment]
[This](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0/contrib/CityscapesSOTA/predict.py) is a template for prediction. It seems that something went wrong when loading data. 

The handling of labels is most suspect. 

Since the dataloader does not generally return labels at prediction time, this error may occur by using the training-time configuration directly.
