### ISSUE TITLE
HRnet-18-w2

### ISSUE THREAD

**Issue by sborse3** [PaddlePaddle/PaddleSeg#1051]
Hi!
Thanks for this repository, I find some aspects quite interesting!

1. Is the FCN-HRNet-18 model with ~79% mIoU the same as HRNet-18-w2 on their official implementation (~76.2% mIoU)? 
2. For Cityscapes, the size of image is 1024x2048, and I see the inference size here is 512x1024. Is there any reason for the size change? Would it be fair comparison with other works to use cropped images for inference?

Thanks!

**Comment by lingorX** [comment]
1. HRNet has several variants, however, the performance gap between them is not very large. An important reason for Paddleseg's improvement over the official implementation is the initialization of parameters. The ssld-based pre-training parameters allow easy progress on a variety of tasks. For details, please move [PaddleClas](https://paddleclas.readthedocs.io/zh_CN/latest/advanced_tutorials/distillation/distillation.html#ssld)
2. Due to the constraint of memory, we reduced the resolution. 
3. Random Resize + Crop is a generic training strategy. Besides semantic segmentation, other tasks such as detection, localization are also used. You can find this strategy in any Cityscape-related repo without hassle.

**Comment by sborse3** [comment]
Hi @0liliulei, thanks for the answers!
From your answer, it seems I misunderstood. Is the training size 1024x512, or inference size 1024x512?

**Comment by lingorX** [comment]
Random Resize + Crop works in training phase. When validating or testing, we maintain the vanilla resolution.

**Comment by sborse3** [comment]
Thanks a lot for the clarification! Yes, this makes perfect sense, sorry for misunderstanding.

Is there a way to find the number of flops for this HRNet-18 model? Could you let me know the appx. flops count expected? Thanks!

**Comment by lingorX** [comment]
I think this [op](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/flops_en.html) will meet your requirements.
