### ISSUE TITLE
EiSeg标注工具模型参数无法加载

### ISSUE THREAD

**Issue by lx11** [PaddlePaddle/PaddleSeg#1546]
在windows10中， 安装paddlepaddel2.2, git clone develop版本EiSeg，然后在EiSeg/eiseg文件中运行python -m eiseg，打开了EiSeg标注界面，然后无法加载模型参数。

**Comment by haoyuying** [comment]
您好，可以截个界面图吗，如果加载不了.pdiparams就还是没有切到0.4版本的问题，0.4的模型选择部分只有加载网络参数
<img width="334" alt="image" src="https://user-images.githubusercontent.com/35907364/141977451-09e69e1a-7330-4423-8da4-4fa7bc88593a.png">
如果你的模型选择界面是和我上面这个图一样，可以贴个界面图，目前怀疑是您使用的不是develop的eiseg，而是release/2.3分支的代码，在clone代码时候要选择分支进行clone。

**Comment by WHUISSZH** [comment]
您好，我在Windows10中直接打开exe文件后加载模型参数文件时发现它加载的文件后缀是*.pdparams，但是下载的模型参数文件里没有*.pdparams结尾的。。。第一次使用，请问这是怎么回事?
![image](https://user-images.githubusercontent.com/34979314/141982287-1aaa5fcb-4684-4b97-a0e8-2066fd65bf1f.png)

**Comment by haoyuying** [comment]
只要加载pdparams都是<=0.3.x的版本，请参考该文档https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.3/EISeg

**Comment by bobopit** [comment]
你好，我在mac上使用eiseg工具，paddle版本0.2.2，通过pip安装的eiseg，版本是0.4.0。界面和您上面的截图是一样的，只有加载网络参数选项，但pdparams加载不进去是为啥呢

**Comment by bobopit** [comment]
![image](https://user-images.githubusercontent.com/26221003/142205603-cb8f3956-e470-44c5-a108-7dd716bf00db.png)

**Comment by linhandev** [comment]
@bobopit eiseg 0.4.0以上版本开始采用静态图，加载的权重是 pdiparams 结尾。您需要重新下载一下模型，地址[在这](https://github.com/PaddleCV-SIG/EISeg#%E6%A8%A1%E5%9E%8B%E5%87%86%E5%A4%87)

**Comment by lx11** [comment]
> 您好，可以截个界面图吗，如果加载不了.pdiparams就还是没有切到0.4版本的问题，0.4的模型选择部分只有加载网络参数 <img alt="image" width="334" src="https://user-images.githubusercontent.com/35907364/141977451-09e69e1a-7330-4423-8da4-4fa7bc88593a.png"> 如果你的模型选择界面是和我上面这个图一样，可以贴个界面图，目前怀疑是您使用的不是develop的eiseg，而是release/2.3分支的代码，在clone代码时候要选择分支进行clone。

非常感谢，确实不是develop的eiseg，重新切换分支后可以加载静态图权重参数。

**Comment by Wangwk1** [comment]
请问大佬们知道为啥我一进去Eiseg界面之后没有反应，过了一会后就自动关了的原因吗

**Comment by linhandev** [comment]
可能是模型加载的问题，运行的是什么版本？是什么方式运行的？可能命令行会有报错

**Comment by GourdTG666** [comment]
大佬，帮我看看这怎么弄？加载模型软件就闪退

INFO 2022-09-02 11:13:54,851 controller.py:111] User paddle compiled with gpu: use_gpu False
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
QObject::~QObject: Timers cannot be stopped from another thread
![image](https://user-images.githubusercontent.com/110643877/188051976-4b4a013d-1ffe-4bee-a38e-ce50cb0aeec9.png)

**Comment by GourdTG666** [comment]
还有点击那个使用掩膜的开关，也闪退

Traceback (most recent call last):
  File "D:\Anaconda\envs\eiseg\PaddleSeg\EISeg\eiseg\app.py", line 966, in chooseMode
    self.controller.reset_predictor(predictor_params=self.predictor_params)
  File "D:\Anaconda\envs\eiseg\PaddleSeg\EISeg\eiseg\controller.py", line 322, in reset_predictor
    if self.model.model:
AttributeError: 'NoneType' object has no attribute 'model'

**Comment by hello-Painkiller** [comment]
> > 您好，可以截个界面图吗，如果加载不了.pdiparams就还是没有切到0.4版本的问题，0.4的模型选择部分只有加载网络参数 <img alt="image" width="334" src="https://user-images.githubusercontent.com/35907364/141977451-09e69e1a-7330-4423-8da4-4fa7bc88593a.png"> 如果你的模型选择界面是和我上面这个图一样，可以贴个界面图，目前怀疑是您使用的不是develop的eiseg，而是release/2.3分支的代码，在clone代码时候要选择分支进行clone。
> 
> 非常感谢，确实不是develop的eiseg，重新切换分支后可以加载静态图权重参数。

你好，具体该如何操作啊，我非专业人士有点搞不懂，我也是导入不了模型进eiseg

**Comment by pimooook** [comment]
> 

您好，请问在哪下载pdiparams结尾的模型权重呢？我只能下载到pdparams的
