### ISSUE TITLE
[General Issue安装出现cannot import name '_C_ops' from partially initialized module 'paddle' (most likely due to a circular import

### ISSUE THREAD

**Issue by pyddyp** [PaddlePaddle/PaddleSeg#2469]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

 1. PaddleSeg版本：PaddleSeg release/2.6
 2. PaddlePaddle版本：v2.3
 3. 操作系统信息：windows
 4. Python版本号：（Python3.10）
 5. CUDA/cuDNN版本：（CUDA10.2）
 6. 其他内容: [General Issue安装出现cannot import name '_C_ops' from partially initialized module 'paddle' (most likely due to a circular import
 7. 
![image](https://user-images.githubusercontent.com/44725093/185629117-89de12fe-da0e-45d6-9e06-e42dcf2dbf67.png)

**Comment by shiyutang** [comment]
This problem is caused by the incorrect installation of paddlepaddle. You need to reinstall paddle according to your device.
If you are using cuda 11.1, you can install it through
`python -m pip install paddlepaddle-gpu==2.3.2.post111 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html`
