### ISSUE TITLE
how to make C++ dll library

### ISSUE THREAD

**Issue by timdeveloper25** [PaddlePaddle/PaddleSeg#3792]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, I am sorry if the question already asked before, maybe asked in Chinese language. 

I found library PaddleSeg.dll from internet, and with some exported function like SegFile, SegInit, ..etc. I need to customize the functionality with my own function that passing parameter as byte array not as a string of path file. 

I am new with C++, and I eager to learn, please help me to give some guidance how to compile the PaddleSeg to C/C++ dll library.

**Comment by Bobholamovic** [comment]
AFAIK, PaddleSeg does not offer official C/C++ APIs. Since PaddleSeg primarily utilizes Paddle Inference APIs for inference and the preprocessing and postprocessing steps are mostly straitforward, creating a DLL for PaddleSeg may not be necessary. Instead, you can refer to the [C++ example](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9.1/docs/deployment/inference/cpp_inference_windows.md) provided by PaddleSeg.  That being said, if you are interested in creating a DLL, here's a [detailed tutorial on how to create and use your own DLL written in MSVC](https://learn.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170). You can optionally build your own DLL based on the PaddleSeg C++ example, by incorporating a modular design and making some adjustments to the code.

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
