### ISSUE TITLE
报错“ValueError: invalid literal for int() with base 10: './saved_model/unet_pet/10”

### ISSUE THREAD

**Issue by lakebodhi** [PaddlePaddle/PaddleSeg#85]
根据[https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.2.0/docs/usage.md](url)的示例操作，执行
`python pdseg/train.py
                      --do_eval \
                      --use_tb \
                      --tb_log_dir train_log \
                      --cfg configs/unet_pet.yaml \
                      BATCH_SIZE 4 \
                      TRAIN.PRETRAINED_MODEL_DIR pretrained_model/unet_bn_coco \
                      SOLVER.LR 5e-5`
程序报错：

> #1 visualize image path: visual\visual_results\Abyssinian_201.png
>Traceback (most recent call last):
  File "pdseg/train.py", line 487, in <module>
    main(args)
  File "pdseg/train.py", line 474, in main
    train(cfg)
  File "pdseg/train.py", line 456, in train
    log_writer=log_writer)
  File "D:\remote_sensing\PaddleSeg\pdseg\vis.py", line 229, in visualize
    epoch = int(ckpt_dir.split(os.path.sep)[-1])
ValueError: invalid literal for int() with base 10: './saved_model/unet_pet/10'

操作系统windows10 64位 cpu训练

**Comment by wuyefeilin** [comment]
@lakebodhi 看样子是你的模型路径”./saved_model/unet_pet/10“与系统的路径分割符不同导致的问题，把路径的分割符改成windows的就可以了

**Comment by nepeplwu** [comment]
@lakebodhi 感谢反馈，该问题已经修复，使用最新代码试试看

**Comment by ArtemiyFirsov** [comment]
Not fixed. 
Getting the same error on Ubuntu 18.04 Docker installation.
Running docker with 
`sudo docker run --gpus=all -it -v $(pwd)/DeepSpeech:/DeepSpeech hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu /bin/bash`

Updated the code to the latest develop branch.

Error happens on infer 
`CUDA_VISIBLE_DEVICES=0 python infer.py --infer_manifest test_deep_speech.txt`

Manifest I am trying to infer 
`{"audio_filepath": "/DeepSpeech/test_deep_speech.wav", "duration": 30.960, "text": ""}`

So it does not even goes to the infer, it fails on data read, because the code tried to convert text to int.

UPDATE: sorry, this is in the DeepSpeech repo

![image](https://user-images.githubusercontent.com/4475110/72521299-c2533a80-388d-11ea-817f-3fcd90fb08d9.png)
